debug: true
auto_reload: false
presets_dir: "sounds"
midi_learn_mode: true

audio:
  driver: "alsa" # alsa | jack | pulseaudio
  device: "default"

  fluidsynth:
    audio.alsa.device: "default"
    audio.period-size: 128
    audio.periods: 3
    synth.cpu-cores: 2
    synth.polyphony: 128
    synth.gain: 0.8

midi:
  input_port: "auto"
  
  cc_map:
    64: "sustain"
    11: "expression"

  actions:
    reload_config:
      cc: 114
      value: 127

    next_bank:
      cc: 112
      value: 127

    prev_bank:
      cc: 111
      value: 127

    panic:
      cc: 118
      value: 127

active_bank: "Live"
banks:
  - name: "Live"
    description: "Configuração para performance ao vivo"
    instruments:
      - name: "Piano"
        file: "sounds/pianos/piano.sf2"
        channel: 0
        bank: 0
        preset: 3
        volume_cc: 1
        initial_volume: 127
        use_sustain: true
        min_note: "C0"
        max_note: "C8"

      - name: "Pad"
        file: "sounds/pads/analog.sf2"
        channel: 1
        bank: 0
        preset: 0
        volume_cc: 2
        initial_volume: 0
        use_sustain: true
        min_note: "C2"
        max_note: "B4"

  - name: "Studio"
    description: "Configuração para gravação"
    instruments:
      - name: "Piano"
        file: "sounds/pianos/piano.sf2"
        channel: 0
        bank: 0
        preset: 3
        volume_cc: 1
        initial_volume: 127
        use_sustain: true
        min_note: "C0"
        max_note: "C8"

      - name: "Organ"
        file: "sounds/organ/virtual.sf2"
        channel: 1
        bank: 100
        preset: 40
        volume_cc: 2
        initial_volume: 0
        use_sustain: false
        min_note: "C1"
        max_note: "C7"

      - name: "Organ 2"
        file: "sounds/organ/organs.sf2"
        channel: 2
        bank: 2
        preset: 17
        volume_cc: 3
        initial_volume: 0
        use_sustain: false
        min_note: "C0"
        max_note: "C8"

  - name: "Ambient"
    description: "Pads e texturas"
    instruments:
      - name: "Pad"
        file: "sounds/pads/analog.sf2"
        channel: 0
        bank: 0
        preset: 0
        volume_cc: 1
        initial_volume: 127
        use_sustain: true
        min_note: "C2"
        max_note: "B5"

http:
  enabled: true
  host: "0.0.0.0"
  port: 5000
