debug: true
auto_reload: true
presets_dir: "sounds"

audio:
  driver: "alsa" # alsa | jack | pulseaudio
  device: "default"

  fluidsynth:
    audio.alsa.device: "default"
    audio.period-size: 128
    audio.periods: 3
    synth.cpu-cores: 2
    synth.polyphony: 128
    synth.gain: 0.8

midi:
  input_port: "auto"

instruments:
  - name: "Piano"
    file: "sounds/pianos/nord-stage-4.sf2"
    channel: 0
    bank: 0
    preset: 3
    volume_cc: 56
    initial_volume: 127
    min_note: "C0"
    max_note: "C8"

  - name: "Pad"
    file: "sounds/pads/analog.sf2"
    channel: 1
    bank: 0
    preset: 0
    volume_cc: 57
    initial_volume: 0
    min_note: "C2"
    max_note: "B3"

  - name: "Electric"
    file: "sounds/electric-pianos/nord.sf2"
    channel: 2
    bank: 0
    preset: 1
    volume_cc: 58
    initial_volume: 0
    min_note: "C0"
    max_note: "C8"

  - name: "Organ"
    file: "sounds/organ/virtual.sf2"
    channel: 3
    bank: 100
    preset: 40
    volume_cc: 59
    initial_volume: 0
    min_note: "C0"
    max_note: "C8"

  - name: "Organ 2"
    file: "sounds/organ/organs.sf2"
    channel: 4
    bank: 2
    preset: 17
    volume_cc: 60
    initial_volume: 0
    min_note: "C0"
    max_note: "C8"

http:
  enabled: true
  host: "0.0.0.0"
  port: 5000
